[package]
authors = ["Dustin Knopoff <dustinknopoff@gmail.com>"]
edition = "2018"
name = "frontmatter"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(wasm)'.dev-dependencies]
wasm-bindgen = "0.2"
