[package]
authors = ["Dustin Knopoff <dustinknopoff@gmail.com>"]
edition = "2018"
include = ["src/lib.rs", "LICENSE", "README.md"]
name = "frontmatter"
version = "0.1.1"

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(wasm)'.dev-dependencies]
wasm-bindgen = "0.2"
